### ISSUE TITLE
element block ID -1

### ISSUE THREAD

**Issue by martinvandriel** [SalvusHub/pyexodus#1]
It seems the element block ID is not properly set: paraview shows it as -1, while it is 1 with the original library. This produces some problems downstream...

to reproduce: build any mesh and open in paraview, the value is shown in the properties tab in the blocks section

**Comment by krischer** [comment]
Fixed in 94210b4ee7ba805f8694a756caa85b169f7713f4 and 04ee5ed5df1bfad45b972646657e672b20633e8d. It can now also correctly write multiple element blocks.
