### ISSUE TITLE
Add package to `pip`?

### ISSUE THREAD

**Issue by daniellivingston** [SalvusHub/pyexodus#10]
This package is great and eliminates a lot of headache for using the Python Exodus API. Can this be added to `pip` such that it would be easier to add as a dependency for other packages?

**Comment by krischer** [comment]
It is on pip: https://pypi.org/project/pyexodus/

Let me know if this does not work for you.

**Comment by daniellivingston** [comment]
Ah, thank you! It may be worth considering adding that to the README or documentation.
