### ISSUE TITLE
meshio

### ISSUE THREAD

**Issue by nschloe** [SalvusHub/pyexodus#9]
This might be obsoleted by [meshio](https://github.com/nschloe/meshio) (a project of mine). meshio has had exodus i/o for a while now.

**Comment by krischer** [comment]
That's probably true. We still use it for a few things internally because it is quite a small dependency. But I'll add a note to this package's readme that meshio is probably a much more useful package for most people.

**Comment by nschloe** [comment]
Note that meshio is also lightweight in that its only hard dependency is on numpy. For exodus, it uses netCDF4. (I'll see if that can be replaced by h5netcdf.)
